### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by balog-b** [kir-dev/epitesz-klub#1]
Create the Navbar. Pay attention to the colors of the dropdown menus

![dropdown](https://github.com/user-attachments/assets/bfefb67b-57f7-460b-bbd2-591b371570bc)

**Comment by Lemeri123** [comment]
hello @balog-b I would like to work on this issue

**Comment by balog-b** [comment]
> hello @balog-b I would like to work on this issue
> 
> 

Hello,

Thank you, but we would like our Organizations members to work on these issues before outsourcing it to others.
